### ISSUE TITLE
ImportError with blender 4.1

### ISSUE THREAD

**Issue by questionkiller** [WistfulHopes/GBFRBlenderTools#27]
`Python: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_gbfr_blender_tools\gbfr_import.py", line 344, in execute
    return read_some_data(context, self.filepath, self.import_scale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_gbfr_blender_tools\gbfr_import.py", line 203, in read_some_data
    mesh1.use_auto_smooth = True
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'use_auto_smooth'
`

**Comment by questionkiller** [comment]
add # at the start of  line 203
